export const AGENT_LLM_TIMEOUT_MS = 60000;
export const AGENT_LLM_RETRY_TIMEOUT_MS = 25000;
export const AGENT_FINAL_ANSWER_TIMEOUT_MS = 25000;
export const AGENT_FINAL_ANSWER_RETRY_TIMEOUT_MS = 12000;
export const AGENT_SUMMARY_TIMEOUT_MS = 90000;
export const AGENT_PLANNER_TIMEOUT_MS = 15000;
export const AGENT_CODE_FETCH_TIMEOUT_MS = 15000;
export const AGENT_REPO_PATH_DISCOVERY_TIMEOUT_MS = 8000;
export const AGENT_TOPIC_PATH_DISCOVERY_TIMEOUT_MS = 12000;
export const AGENT_LOOP_MAX_ITERATIONS = 3;

const AGENT_RUNTIME_MESSAGE_BUFFER_MS = 30000;

export function getAgentWorstCaseRuntimeTimeoutMs(): number {
  return (
    AGENT_PLANNER_TIMEOUT_MS +
    Math.max(AGENT_REPO_PATH_DISCOVERY_TIMEOUT_MS, AGENT_TOPIC_PATH_DISCOVERY_TIMEOUT_MS) +
    AGENT_CODE_FETCH_TIMEOUT_MS +
    AGENT_LOOP_MAX_ITERATIONS * AGENT_PLANNER_TIMEOUT_MS +
    AGENT_FINAL_ANSWER_TIMEOUT_MS +
    AGENT_FINAL_ANSWER_RETRY_TIMEOUT_MS
  );
}

export const AGENT_CHAT_REQUEST_TIMEOUT_MS = Math.max(
  180000,
  getAgentWorstCaseRuntimeTimeoutMs() + AGENT_RUNTIME_MESSAGE_BUFFER_MS
);
